### ISSUE TITLE
Do not use 'Out of phase' description in output

### ISSUE THREAD

**Issue by dkutalek** [rh-lab-q/bkrdoc#10]
It seems that using just indentation is cleaner and more acceptable way to go for out-of-phase bkrdoc comments.

**Comment by Jurisak** [comment]
I pushed modification to fix this issue. Could you please test it? Thanks.

**Comment by dkutalek** [comment]
Thanks, basically works for me. The only cosmetic thing is this:
with initial markup before first phase, with additional information turned on, it outputs:

---
Description: Test for BZ#833170 (sosreport doesn't pick up biosdevname named interfaces)
Author: David Kutalek <dkutalek@redhat.com>
Keywords: 

Phases:
b
c

  Setup 
    phase description
---

It would be nicer for typical use case to move line Phases: just before the first phase line, not before first comments.

**Comment by dkutalek** [comment]
My last comment is basically issue #9, sorry for confusion. Therefore closing this one as working, thanks.
