### ISSUE TITLE
Make 'Additional section' part of output as optional (off by default)

### ISSUE THREAD

**Issue by dkutalek** [rh-lab-q/bkrdoc#11]
So far it is more confusing then value adding, therefore please turn it off by default.

**Comment by dkutalek** [comment]
Also, when having Additional information section disabled, 'Phases' header should be omitted (no need for it then)

**Comment by Jurisak** [comment]
I pushed modification to fix this issue. Could you please test it? Thanks.

**Comment by dkutalek** [comment]
Thanks, works for me.
