### ISSUE TITLE
bkrdoc(analysis): Better labels for documentation credibility

### ISSUE THREAD

**Issue by Jurisak** [rh-lab-q/bkrdoc#6]
Nowadays bkrdoc presents information about credibility in form of unrecognized command lines in BeakerLib phase. Looks like this: `Cleanup "Cleanup" [ Unknown commands: 1, Total: 4 ]`. I think those information should be rewritten to give better information and at the end of documentation put line or two about whole documentation credibility. (If the whole documentation credibility information will be in good shape and will provide reliable information about documentation credibility then information about BeakerLib phases could be removed. Maybe?) 

Possible way how to fix it:
1) Create class DocumentationCredibily which will contain documentation credibility templates(Instance variables or methods).  Marked from zero to five(HIGH  to LOW). For example zero version should tell that the whole documentation is highly unreliable and fifth version should tell that it is highly reliable. Something like that...

2) Modify method print_phase_name_with_documentation_credibility in data_containers.py/PhaseContainer to provide better BeakerLib phase credibility information(Templates for BeakerLib phase credibility information could be in DocumentationCredibility class as well). 

3) Create method in data_containers.py/PhaseContainer to return BeakerLib phase credibility.

4) Create method in documentation_generator.py/DocumentationGenerator which will take care about creation of Documentation credibility information.(Should call in cycle method made in step 3 and sums up the whole documentation result). At the end add the call of this method at the end of  documentation_generator.py/DocumentationGenerator/print_documentation method

**Comment by petr-muller** [comment]
What else is to do here?

[--- Commented from Asana.com
#commenter Zuzana Baranova
---[aa]

**Comment by petr-muller** [comment]
From my perspective It could be all ... If you think that all implementations are made then close this task :smile:

[--- Commented from Asana.com
#commenter Jiří Kulda
---[aa]
