### ISSUE TITLE
Markup: Smart way to document rl* commands

### ISSUE THREAD

**Issue by dkutalek** [rh-lab-q/bkrdoc#7]
Most of beakerlib rl* commands contains some kind of documentation string.
Please implement a smart way of reusing these strings for documentation:
- use empty bkrdoc comment at the end of rl command line to use its string for documentation
- any non-empty bkrdoc comment on the same place means processing as usual

Example:

rlRun 'ps aux' 'ps command should not traceback' #@

should produce one line of documentation like:
ps command should not traceback

On the other hand
rlRun 'ps aux' 'ps command should not traceback' #@ check for traceback

should produce:
check for traceback

**Comment by Jurisak** [comment]
I added implementation of this issue. Could you please test it???

**Comment by lukaszachy** [comment]
Thanks, works.
